apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-db-camellia-test
  labels:
    app: pod-db-camellia-test
spec:
  replicas: 1
  serviceName: svc-db-camellia-test
  selector:
    matchLabels:
      app: pod-db-camellia-test
  template:
    metadata:
      labels:
        app: pod-db-camellia-test
    spec:
      enableServiceLinks: false
      containers:
      - name: container-camellia
        image: 48n6e/camellia-redis-proxy:1.3.6-jdk-21-0.0.1
        command:
        - java
        - "-XX:+UseG1GC"
        - "-XX:+UseContainerSupport"
        - "-Dio.netty.tryReflectionSetAccessible=true" 
        - "--add-opens"
        - "java.base/java.lang=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.io=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.math=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.net=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.nio=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.security=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.text=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.time=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/java.util=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/jdk.internal.access=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/jdk.internal.misc=ALL-UNNAMED" 
        - "--add-opens"
        - "java.base/sun.net.util=ALL-UNNAMED"
        - "-Xms128m"
        - "-Xmx4096m"
        - "-server"
        - "org.springframework.boot.loader.JarLauncher"
        resources:
          requests:
            memory: "128Mi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        ports:
          - containerPort: 6380
            name: db
            protocol: TCP
        volumeMounts:
        - name: cm-db-camellia-test
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/application.yml
          subPath: application-sharding-singlewrite-multiread.yml
        # - name: cm-db-camellia-test
        #   mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/logback.xml
        #   subPath: logback.xml
        # - name: cm-db-camellia-test
        #   mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/camellia-redis-proxy.properties
        #   subPath: camellia-redis-proxy.properties
        - name: cm-db-camellia-test
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/resource-sharding-singlewrite-multiread.json
          subPath: resource-sharding-singlewrite-multiread.json
      volumes:
      - name: cm-db-camellia-test
        configMap:
          name: cm-db-camellia-test
